spring:
  application:
    name: fretemais-driver-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fretemais}
    username: ${DB_USERNAME:fretemais}
    password: ${DB_PASSWORD:fretemais}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:true}

  flyway:
    enabled: true
    baseline-on-migrate: true

security:
  jwt:
    secret: dev-secret-key-dev-secret-key-dev-secret-key
    expiration: 3600000
