spring:
  application:
    name: fretemais-driver-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fretemais}
    username: ${DB_USERNAME:fretemais}
    password: ${DB_PASSWORD:fretemais}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:true}

  flyway:
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET:dev-secret}
    expiration: 3600000
